#TIPOS DE DADOS PRIMITIVOS / PYTHON
##INT PARA NÚMEROS INTEIROS. EX: 7, 0, -4
##FLOAT SERVE PARA OS NÚMEROS REAIS. EX: 0,45. 6,7
##BOOL SERVE PARA VALORES LÓGICOS DE VERDADEIRO OU FALSO. EX: True ou False(sempre usar com a letra maiúscula)
##STR SERVE PARA 'STRINGS' QUE SÃO PALAVRAS, CARACTERES OU TEXTOS. EX: 'ola'. '7.5'
##PARA SABER O TIPO DE UMA VARIÁVEL PODE SE USAR O COMANDO PRINT (type(variavel))
